name: Test Build

on:
  # Runs on pushes to any branch
  push:
    branches: ['*']
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "test-build"
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Build
        run: yarn build
